第３回課題
chihiro0612/RaiseTech pull request #5
Opened 2023-07-20 12:20 UTC by chihiro0612

2023-07-20 12:38 UTC, MasatoshiMizumoto requested changes
画像もpushしてください！

2023-07-22 05:59 UTC, MasatoshiMizumoto requested changes
画像はアップできてますけどmarkdownから見てリンク切れですね！
pathをご確認ください！

2023-07-22 06:40 UTC, chihiro0612 commented
> 画像はアップできてますけどmarkdownから見てリンク切れですね！ pathをご確認ください！

markdownから見てリンク切れというのはmarkdownが見れなくなってるってことですか？

2023-07-22 13:49 UTC, MasatoshiMizumoto requested changes
中身はOKですね！
あとは見出しのスタイリングだけお願いします！

2023-07-22 13:49 UTC, MasatoshiMizumoto commented on lecture03.md
> +#第３回課題
```suggestion
# 第3回課題
```

2023-07-22 13:49 UTC, MasatoshiMizumoto commented on lecture03.md
> + ##Ruby on RailsによるWebアプリケーションの起動
```suggestion
## Ruby on RailsによるWebアプリケーションの起動
```

2023-07-22 13:49 UTC, MasatoshiMizumoto commented on lecture03.md
> +##学んだこと
```suggestion
## 学んだこと
```

2023-07-22 13:49 UTC, MasatoshiMizumoto commented on lecture03.md
> +##課題
```suggestion
## 課題
```

2023-07-22 14:01 UTC, MasatoshiMizumoto approved these changes
LGTM!

![LGTM](https://image.lgtmoon.dev/95929)

2023-07-22 14:04 UTC, merged